export const bundleVarietyPack = [
  {
    product: {
      id: 'blendjet.myshopify.com::jetpack-smoothies::en-us',
      handle: 'jetpack-smoothies',
      locale: 'en-us',
      globalHandle: 'jetpack-smoothies::en-us',
      pimSyncSourceDomain: 'blendjet.myshopify.com',
      title: 'JetPack Smoothie',
      description:
        '<meta charset="utf-8"><span data-mce-fragment="1">Meet JetPack, the incredibly convenient ready-to-blend smoothie designed for your BlendJet portable blender.</span>',
      priceRange: { min: '3.99', max: '3.99', currencyCode: 'USD' },
      availableForSale: true,
      tags: ['jet', 'JetPack', 'OG', 'pack', 'standard'],
      media: [
        {
          id: 'Z2lkOi8vc2hvcGlmeS9JbWFnZVNvdXJjZS8yMDMxMjc0NzM3NjcwNg==',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Banana-Blueberry_JetPack_b9c06246-a52e-47b1-b844-bdb3d405ec1c.png?v=1618354834&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Banana-Blueberry_JetPack_b9c06246-a52e-47b1-b844-bdb3d405ec1c.png?v=1618354834',
          type: 'image',
          altText: null,
        },
        {
          id: 'Z2lkOi8vc2hvcGlmeS9JbWFnZVNvdXJjZS8yMDMxMjc0NzYwNjA4Mg==',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Raspberry-Dragon-Fruit_JetPack_3270bf69-fbdd-4c82-8930-8c621fc13280.png?v=1618354834&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Raspberry-Dragon-Fruit_JetPack_3270bf69-fbdd-4c82-8930-8c621fc13280.png?v=1618354834',
          type: 'image',
          altText: null,
        },
        {
          id: 'Z2lkOi8vc2hvcGlmeS9JbWFnZVNvdXJjZS8yMDMxMjc0Nzc2OTkyMg==',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Green-Peach-Ginger_JetPack_8ca2b91b-5698-4952-b5c2-2ec996e79911.png?v=1618354834&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Green-Peach-Ginger_JetPack_8ca2b91b-5698-4952-b5c2-2ec996e79911.png?v=1618354834',
          type: 'image',
          altText: null,
        },
        {
          id: 'Z2lkOi8vc2hvcGlmeS9JbWFnZVNvdXJjZS8yMDMxMjc0Nzk2NjUzMA==',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Mango-Matcha_JetPack_2cf093b9-fb41-4f5a-b7ae-a82522032da4.png?v=1618354834&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Mango-Matcha_JetPack_2cf093b9-fb41-4f5a-b7ae-a82522032da4.png?v=1618354834',
          type: 'image',
          altText: null,
        },
        {
          id: 'Z2lkOi8vc2hvcGlmeS9JbWFnZVNvdXJjZS8yMDMxMjc0ODEzMDM3MA==',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Mocha-Chia_JetPack_81b29c34-fc20-45a5-8b05-bd3fd7a3ccff.png?v=1618354834&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Mocha-Chia_JetPack_81b29c34-fc20-45a5-8b05-bd3fd7a3ccff.png?v=1618354834',
          type: 'image',
          altText: null,
        },
        {
          id: 'Z2lkOi8vc2hvcGlmeS9JbWFnZVNvdXJjZS8yMDMxMjc0ODE2MzEzOA==',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Tropical-Blue_JetPack_2dac4156-4df6-45ae-909d-129799813ac9.png?v=1618354834&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Tropical-Blue_JetPack_2dac4156-4df6-45ae-909d-129799813ac9.png?v=1618354834',
          type: 'image',
          altText: null,
        },
      ],
      metafields: [
        {
          id: null,
          namespace: 'subscriptions',
          key: 'discount_percentage',
          value: '25.0000000000',
        },
        {
          id: null,
          namespace: 'subscriptions',
          key: 'subscription_id',
          value: '296970',
        },
        {
          id: null,
          namespace: 'subscriptions',
          key: 'shipping_interval_frequency',
          value: '30',
        },
        {
          id: null,
          namespace: 'subscriptions',
          key: 'shipping_interval_unit_type',
          value: 'Days',
        },
        {
          id: null,
          namespace: 'subscriptions',
          key: 'discount_product_id',
          value: '6561748484162',
        },
        {
          id: null,
          namespace: 'subscriptions',
          key: 'is_subscription_only',
          value: 'false',
        },
        {
          id: null,
          namespace: 'subscriptions',
          key: 'original_to_hidden_variant_map',
          value:
            '{"39289167282242": {"discount_variant_id": 39300894261314, "discount_variant_price": "2.99"}, "39289167315010": {"discount_variant_id": 39300894294082, "discount_variant_price": "2.99"}, "39289167347778": {"discount_variant_id": 39300894326850, "discount_variant_price": "2.99"}, "39289167380546": {"discount_variant_id": 39300894359618, "discount_variant_price": "2.99"}, "39289167413314": {"discount_variant_id": 39300894392386, "discount_variant_price": "2.99"}, "39289167446082": {"discount_variant_id": 39300894425154, "discount_variant_price": "2.99"}}',
        },
        { id: null, namespace: 'loox', key: 'num_reviews', value: '4157' },
        { id: null, namespace: 'loox', key: 'avg_rating', value: '4.9' },
        {
          id: null,
          namespace: 'loox',
          key: 'reviews',
          value:
            '<div id="loox-inline-reviews" style="display:none" data-loox-hash="1637894795462"><div class="review"><div class="name">Thomas L.</div><div class="review_text">All the JetPacks taste absolutely amazing and I have nothing to complain about.</div></div><div class="review"><div class="name">Judy B.</div><div class="review_text">Sent some to my niece as well.</div></div><div class="review"><div class="name">Christina M.</div><div class="review_text">Convenient and great for on the go days when I don’t want a hefty meal</div></div><div class="review"><div class="name">Alexa A.</div><div class="review_text">this is my fav flavor; it\'s great!</div></div><div class="review"><div class="name">Sam P.</div><div class="review_text">I always like to make sure my shoes match my blendjet… #coordination</div></div><div class="review"><div class="name">Miranda S.</div><div class="review_text">It taste good with mocha  when my sugar is low I drink it  I think it helps  </div></div><div class="review"><div class="name">Graham I.</div><div class="review_text">Awesome packets really worth it instead of trying to get all the ingredients yourself . It makes it simple and includes more than simple whey protein . Love these!!!!</div></div><div class="review"><div class="name">Jacqueline G.</div><div class="review_text">I like all of them and I love my Blend Jet use it all the time.</div></div><div class="review"><div class="name">Alan B.</div><div class="review_text">Creates great smooothies from milk and fresh or frozen fruit in seconds...I am delighted with it.</div></div><div class="review"><div class="name">Sara H.</div><div class="review_text">This is so smooth and refreshing!</div></div><div class="review"><div class="name">gloria o.</div><div class="review_text">Love the smoothies</div></div><div class="review"><div class="name">Joyous J.</div><div class="review_text">This is my all-time favorite shake. It\'s the best flavor of them all </div></div><div class="review"><div class="name">Dana B.</div><div class="review_text">I enjoy them</div></div><div class="review"><div class="name">Rita T.</div><div class="review_text">I love the shakes from BlendJet, they are easy to make and very convenient to take anywhere.</div></div><div class="review"><div class="name">Sherry J.</div><div class="review_text">It is so easy to slip into my gym bag and use after my workout. All I do is ask for some ice. </div></div><div class="review"><div class="name">Christina D.</div><div class="review_text">fast and quiet..</div></div><div class="review"><div class="name">Steve W.</div><div class="review_text">My meal replacement depends on blendjet</div></div><div class="review"><div class="name">Joyce K.</div><div class="review_text">Convenient and user friendly :)</div></div><div class="review"><div class="name">Desiree L.</div><div class="review_text">Got this for my 10yr olds birthday she loved the smoothie she mixed it with peach and Orange juice she saidd it was 10 out of 10! \n</div></div><div class="review"><div class="name">Tracey D.</div><div class="review_text">I used apple juice with this blend and it was so much better than the previous blend I bought. It was much smoother, with no graininess. The flavor was bright and it smelled good, as well.</div></div><div class="review"><div class="name">Nancy O.</div><div class="review_text">Love it </div></div><div class="review"><div class="name">Lorena S.</div><div class="review_text">Love it!</div></div><div class="review"><div class="name">Mary M.</div><div class="review_text">I use my blend jet to mix the jet pack with some other goodies like protein powder, collagen, and blue pea powder. Blend, stir in chia seeds and let sit until it turns into a pudding. Then, I serve it up with fruit and it makes an incredible lunch! </div></div><div class="review"><div class="name">Theresa H.</div><div class="review_text">I like the blend jet things you send me in the mail especially the blueberry and banana.</div></div><div class="review"><div class="name">Laurie B.</div><div class="review_text">really great experience </div></div><div class="review"><div class="name">Oona M.</div><div class="review_text">I love my BlendJet! It goes everywhere with me - home, gym, work, hiking, the car, you name it. I love the hands-free blending and how easy it is to clean. And it really DOES blast ice cubes to smithereens! Charge lasts a good long while. </div></div><div class="review"><div class="name">gloria o.</div><div class="review_text">Love this flavor. I add frozen blueberries and raspberries with ice &amp; yumm so filling!</div></div><div class="review"><div class="name">Christine S.</div><div class="review_text">Love the flavor</div></div><div class="review"><div class="name">Debbie T.</div><div class="review_text">I am very surprised how awesome the smoothies tastes. And the Blend Jet mixer machine is also awesome and easy to use and keep clean.</div></div><div class="review"><div class="name">Beverly H.</div><div class="review_text">Very good </div></div><div class="review"><div class="name">Vert-pre S.</div><div class="review_text">Commande bien reçu \nMerci beaucoup\n</div></div><div class="review"><div class="name">Carol A.</div><div class="review_text">My grandson loves making his own smoothies.  He takes it to his classes in college.</div></div><div class="review"><div class="name">Star Z.</div><div class="review_text">I like this flavor!</div></div><div class="review"><div class="name">Matthias H.</div><div class="review_text">Very tasty and quick to make! I use it as my breakfast replacement and have felt a lot more energized for the day.</div></div><div class="review"><div class="name">TAKAO M.</div><div class="review_text">I like to make Frappuccino.\nYour Recipes Book is excellent!!</div></div><div class="review"><div class="name">Sheba L.</div><div class="review_text">Love that it stays fresh till lunchtime! </div></div><div class="review"><div class="name">Sheba L.</div><div class="review_text">It\'s a brilliant product. So versatile and cool\n</div></div><div class="review"><div class="name">carlos alberto s.</div><div class="review_text">excelente</div></div><div class="review"><div class="name">Corey C.</div><div class="review_text">Super easy, convenient, and delicious! I had fresh fruit to the smoothie packs and it beats any juice bar or $7 smoothie shop.</div></div><div class="review"><div class="name">Dawn E.</div><div class="review_text">I carry this everywhere and the green peach ginger is so tasty. </div></div><div class="review"><div class="name">Dawn E.</div><div class="review_text">Loving this little machine. So much handheld power. </div></div><div class="review"><div class="name">Alysa W.</div><div class="review_text">These smoothies are delicious and so easy to make</div></div><div class="review"><div class="name">Dana P.</div><div class="review_text">Love the tropical blue jet pack! Taste great  and love using my blendjet ❤️</div></div><div class="review"><div class="name">Dana P.</div><div class="review_text">I absolutely love my blendjet so convenient, quick clean up, and love the jet packs the Green Peach Ginger is one of my favorites</div></div><div class="review"><div class="name">Yulanda G.</div><div class="review_text">I love it very much. Excellent product.</div></div><div class="review"><div class="name">Jacqueline G.</div><div class="review_text">I really love the taste of the Jet packs </div></div><div class="review"><div class="name">Lena B.</div><div class="review_text">Best purchase I have made in a long time!</div></div><div class="review"><div class="name">Marilyn W.</div><div class="review_text">I also sent one to my son for his birthday. He loves it.</div></div><div class="review"><div class="name">gloria o.</div><div class="review_text">I love it and use it everyday twice.\nSo easy to use and clean! Can’t live without my Blendjet!</div></div><div class="review"><div class="name">Deloris R.</div><div class="review_text">I am 81 years old and I love my Blendjet and jet packs. After 3 weeks I can tell a difference \nIn my weight and digestive system. Lol old people talk about health. I can carry it easily and\nLove the clean up. They jet pack’s are the best I have ever tested. Market to baby boomers \nAnd older market. Thank you for a wonderful customer service dept.\nLove your web site\nDee Roberson</div></div><div class="review"><div class="name">Miranda S.</div><div class="review_text">Mocha is good flavor  wish u guy have.  More Selections like peanut butter and chocolate smoothies. </div></div><div class="review"><div class="name">Jacqueline G.</div><div class="review_text">I love the Blend Jet and the Jet Packs I use both every day.</div></div><div class="review"><div class="name">Maria C.</div><div class="review_text">I love it  </div></div><div class="review"><div class="name">Christina A.</div><div class="review_text">Delicious and so convenient. Reminded me of a piña colada</div></div><div class="review"><div class="name">Christina A.</div><div class="review_text">Delicious and so convenient </div></div><div class="review"><div class="name">Mason C.</div><div class="review_text">We love the ease of making breakfast every morning! No sacrificing taste.</div></div><div class="review"><div class="name">Rosalind H.</div><div class="review_text">My blendjet is the best! Can\'t do without it</div></div><div class="review"><div class="name">Debra j N.</div><div class="review_text">Powerful little blenderjet </div></div><div class="review"><div class="name">Brittany  .</div><div class="review_text">My second favorite smoothie! </div></div><div class="review"><div class="name">Brittany  .</div><div class="review_text">This is my favorite out of all of them! I add coconut water, ice and the jet pack and I’m done so simple!</div></div><div class="review"><div class="name">Kimberly M.</div><div class="review_text">I really like how convenient and easy they are to use.  </div></d... (10024 total length)',
        },
      ],
      variants: [
        {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zOTI4OTE2NzI4MjI0Mg==',
          title: 'Banana Blueberry',
          price: '3.99',
          priceCurrency: 'USD',
          compareAtPrice: null,
          compareAtPriceCurrency: null,
          swatchSrc: null,
          selectedOptions: [{ name: 'Flavor', value: 'Banana Blueberry' }],
          featuredMedia: {
            id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMjgwMTIxMjE5MTU0NTg=',
            thumbnailSrc:
              'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Banana-Blueberry_JetPack_b9c06246-a52e-47b1-b844-bdb3d405ec1c.png?v=1618354834&width=100',
            src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Banana-Blueberry_JetPack_b9c06246-a52e-47b1-b844-bdb3d405ec1c.png?v=1618354834',
            type: 'image',
            altText: null,
          },
          sku: 'JP-Banana-Blueberry',
          availableForSale: true,
          metafields: [],
          weight: 1.375,
          weightUnit: 'OUNCES',
          priceRules: null,
        },
        {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zOTI4OTE2NzMxNTAxMA==',
          title: 'Raspberry Dragon Fruit',
          price: '3.99',
          priceCurrency: 'USD',
          compareAtPrice: null,
          compareAtPriceCurrency: null,
          swatchSrc: null,
          selectedOptions: [
            { name: 'Flavor', value: 'Raspberry Dragon Fruit' },
          ],
          featuredMedia: {
            id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMjgwMTIxMjIxNDQ4MzQ=',
            thumbnailSrc:
              'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Raspberry-Dragon-Fruit_JetPack_3270bf69-fbdd-4c82-8930-8c621fc13280.png?v=1618354834&width=100',
            src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Raspberry-Dragon-Fruit_JetPack_3270bf69-fbdd-4c82-8930-8c621fc13280.png?v=1618354834',
            type: 'image',
            altText: null,
          },
          sku: 'JP-Raspberry-Dragon-Fruit',
          availableForSale: true,
          metafields: [],
          weight: 1.375,
          weightUnit: 'OUNCES',
          priceRules: null,
        },
        {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zOTI4OTE2NzM0Nzc3OA==',
          title: 'Green Peach Ginger',
          price: '3.99',
          priceCurrency: 'USD',
          compareAtPrice: null,
          compareAtPriceCurrency: null,
          swatchSrc: null,
          selectedOptions: [{ name: 'Flavor', value: 'Green Peach Ginger' }],
          featuredMedia: {
            id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMjgwMTIxMjIyNDMxMzg=',
            thumbnailSrc:
              'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Green-Peach-Ginger_JetPack_8ca2b91b-5698-4952-b5c2-2ec996e79911.png?v=1618354834&width=100',
            src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Green-Peach-Ginger_JetPack_8ca2b91b-5698-4952-b5c2-2ec996e79911.png?v=1618354834',
            type: 'image',
            altText: null,
          },
          sku: 'JP-Green-Peach',
          availableForSale: true,
          metafields: [],
          weight: 1.375,
          weightUnit: 'OUNCES',
          priceRules: null,
        },
        {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zOTI4OTE2NzM4MDU0Ng==',
          title: 'Mango Matcha',
          price: '3.99',
          priceCurrency: 'USD',
          compareAtPrice: null,
          compareAtPriceCurrency: null,
          swatchSrc: null,
          selectedOptions: [{ name: 'Flavor', value: 'Mango Matcha' }],
          featuredMedia: {
            id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMjgwMTIxMjI1MDUyODI=',
            thumbnailSrc:
              'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Mango-Matcha_JetPack_2cf093b9-fb41-4f5a-b7ae-a82522032da4.png?v=1618354834&width=100',
            src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Mango-Matcha_JetPack_2cf093b9-fb41-4f5a-b7ae-a82522032da4.png?v=1618354834',
            type: 'image',
            altText: null,
          },
          sku: 'JP-Mango-Matcha',
          availableForSale: true,
          metafields: [],
          weight: 1.375,
          weightUnit: 'OUNCES',
          priceRules: null,
        },
        {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zOTI4OTE2NzQxMzMxNA==',
          title: 'Mocha Chia',
          price: '3.99',
          priceCurrency: 'USD',
          compareAtPrice: null,
          compareAtPriceCurrency: null,
          swatchSrc: null,
          selectedOptions: [{ name: 'Flavor', value: 'Mocha Chia' }],
          featuredMedia: {
            id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMjgwMTIxMjI2NjkxMjI=',
            thumbnailSrc:
              'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Mocha-Chia_JetPack_81b29c34-fc20-45a5-8b05-bd3fd7a3ccff.png?v=1618354834&width=100',
            src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Mocha-Chia_JetPack_81b29c34-fc20-45a5-8b05-bd3fd7a3ccff.png?v=1618354834',
            type: 'image',
            altText: null,
          },
          sku: 'JP-Mocha-Chia',
          availableForSale: true,
          metafields: [],
          weight: 1.375,
          weightUnit: 'OUNCES',
          priceRules: null,
        },
        {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zOTI4OTE2NzQ0NjA4Mg==',
          title: 'Tropical Blue',
          price: '3.99',
          priceCurrency: 'USD',
          compareAtPrice: null,
          compareAtPriceCurrency: null,
          swatchSrc: null,
          selectedOptions: [{ name: 'Flavor', value: 'Tropical Blue' }],
          featuredMedia: {
            id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMjgwMTIxMjI3MDE4OTA=',
            thumbnailSrc:
              'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Tropical-Blue_JetPack_2dac4156-4df6-45ae-909d-129799813ac9.png?v=1618354834&width=100',
            src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Tropical-Blue_JetPack_2dac4156-4df6-45ae-909d-129799813ac9.png?v=1618354834',
            type: 'image',
            altText: null,
          },
          sku: 'JP-Tropical-Blue',
          availableForSale: true,
          metafields: [],
          weight: 1.375,
          weightUnit: 'OUNCES',
          priceRules: null,
        },
      ],
      indexedAt: 1638192811,
      pimSyncSource: 'shopify',
      pimSyncSourceProductId:
        'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzY1NTU2NjUzMzQzMzg=',
      productType: 'Jetpack Smoothies',
      featuredMedia: {
        id: 'Z2lkOi8vc2hvcGlmeS9JbWFnZVNvdXJjZS8yMDMxMjc0NzM3NjcwNg==',
        thumbnailSrc:
          'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Banana-Blueberry_JetPack_b9c06246-a52e-47b1-b844-bdb3d405ec1c.png?v=1618354834&width=100',
        src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Banana-Blueberry_JetPack_b9c06246-a52e-47b1-b844-bdb3d405ec1c.png?v=1618354834',
        type: 'image',
        altText: null,
      },
      vendor: 'BlendJet',
      createdAt: 1617643543,
    },
    variants: [
      {
        id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zOTI4OTE2NzI4MjI0Mg==',
        title: 'Banana Blueberry',
        price: '3.99',
        priceCurrency: 'USD',
        compareAtPrice: null,
        compareAtPriceCurrency: null,
        swatchSrc: null,
        selectedOptions: [{ name: 'Flavor', value: 'Banana Blueberry' }],
        featuredMedia: {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMjgwMTIxMjE5MTU0NTg=',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Banana-Blueberry_JetPack_b9c06246-a52e-47b1-b844-bdb3d405ec1c.png?v=1618354834&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Banana-Blueberry_JetPack_b9c06246-a52e-47b1-b844-bdb3d405ec1c.png?v=1618354834',
          type: 'image',
          altText: null,
        },
        sku: 'JP-Banana-Blueberry',
        availableForSale: true,
        metafields: [],
        weight: 1.375,
        weightUnit: 'OUNCES',
        priceRules: null,
      },
      {
        id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zOTI4OTE2NzMxNTAxMA==',
        title: 'Raspberry Dragon Fruit',
        price: '3.99',
        priceCurrency: 'USD',
        compareAtPrice: null,
        compareAtPriceCurrency: null,
        swatchSrc: null,
        selectedOptions: [{ name: 'Flavor', value: 'Raspberry Dragon Fruit' }],
        featuredMedia: {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMjgwMTIxMjIxNDQ4MzQ=',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Raspberry-Dragon-Fruit_JetPack_3270bf69-fbdd-4c82-8930-8c621fc13280.png?v=1618354834&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Raspberry-Dragon-Fruit_JetPack_3270bf69-fbdd-4c82-8930-8c621fc13280.png?v=1618354834',
          type: 'image',
          altText: null,
        },
        sku: 'JP-Raspberry-Dragon-Fruit',
        availableForSale: true,
        metafields: [],
        weight: 1.375,
        weightUnit: 'OUNCES',
        priceRules: null,
      },
      {
        id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zOTI4OTE2NzM0Nzc3OA==',
        title: 'Green Peach Ginger',
        price: '3.99',
        priceCurrency: 'USD',
        compareAtPrice: null,
        compareAtPriceCurrency: null,
        swatchSrc: null,
        selectedOptions: [{ name: 'Flavor', value: 'Green Peach Ginger' }],
        featuredMedia: {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMjgwMTIxMjIyNDMxMzg=',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Green-Peach-Ginger_JetPack_8ca2b91b-5698-4952-b5c2-2ec996e79911.png?v=1618354834&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Green-Peach-Ginger_JetPack_8ca2b91b-5698-4952-b5c2-2ec996e79911.png?v=1618354834',
          type: 'image',
          altText: null,
        },
        sku: 'JP-Green-Peach',
        availableForSale: true,
        metafields: [],
        weight: 1.375,
        weightUnit: 'OUNCES',
        priceRules: null,
      },
      {
        id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zOTI4OTE2NzM4MDU0Ng==',
        title: 'Mango Matcha',
        price: '3.99',
        priceCurrency: 'USD',
        compareAtPrice: null,
        compareAtPriceCurrency: null,
        swatchSrc: null,
        selectedOptions: [{ name: 'Flavor', value: 'Mango Matcha' }],
        featuredMedia: {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMjgwMTIxMjI1MDUyODI=',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Mango-Matcha_JetPack_2cf093b9-fb41-4f5a-b7ae-a82522032da4.png?v=1618354834&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Mango-Matcha_JetPack_2cf093b9-fb41-4f5a-b7ae-a82522032da4.png?v=1618354834',
          type: 'image',
          altText: null,
        },
        sku: 'JP-Mango-Matcha',
        availableForSale: true,
        metafields: [],
        weight: 1.375,
        weightUnit: 'OUNCES',
        priceRules: null,
      },
      {
        id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zOTI4OTE2NzQxMzMxNA==',
        title: 'Mocha Chia',
        price: '3.99',
        priceCurrency: 'USD',
        compareAtPrice: null,
        compareAtPriceCurrency: null,
        swatchSrc: null,
        selectedOptions: [{ name: 'Flavor', value: 'Mocha Chia' }],
        featuredMedia: {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMjgwMTIxMjI2NjkxMjI=',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Mocha-Chia_JetPack_81b29c34-fc20-45a5-8b05-bd3fd7a3ccff.png?v=1618354834&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Mocha-Chia_JetPack_81b29c34-fc20-45a5-8b05-bd3fd7a3ccff.png?v=1618354834',
          type: 'image',
          altText: null,
        },
        sku: 'JP-Mocha-Chia',
        availableForSale: true,
        metafields: [],
        weight: 1.375,
        weightUnit: 'OUNCES',
        priceRules: null,
      },
      {
        id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zOTI4OTE2NzQ0NjA4Mg==',
        title: 'Tropical Blue',
        price: '3.99',
        priceCurrency: 'USD',
        compareAtPrice: null,
        compareAtPriceCurrency: null,
        swatchSrc: null,
        selectedOptions: [{ name: 'Flavor', value: 'Tropical Blue' }],
        featuredMedia: {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMjgwMTIxMjI3MDE4OTA=',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Tropical-Blue_JetPack_2dac4156-4df6-45ae-909d-129799813ac9.png?v=1618354834&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Tropical-Blue_JetPack_2dac4156-4df6-45ae-909d-129799813ac9.png?v=1618354834',
          type: 'image',
          altText: null,
        },
        sku: 'JP-Tropical-Blue',
        availableForSale: true,
        metafields: [],
        weight: 1.375,
        weightUnit: 'OUNCES',
        priceRules: null,
      },
    ],
    title: 'BLENDJET 2 + SLEEVE + 6 JETPACKS',
    media: {
      metadata: { tags: [] },
      sys: {
        space: { sys: { type: 'Link', linkType: 'Space', id: 'strhx3d94c40' } },
        id: '4T2g8Y5ZWvb41wRGxAlXky',
        type: 'Asset',
        createdAt: '2020-10-28T02:24:05.980Z',
        updatedAt: '2020-10-28T02:24:05.980Z',
        environment: {
          sys: { id: 'master', type: 'Link', linkType: 'Environment' },
        },
        revision: 1,
        locale: 'en-US',
      },
      fields: {
        title: '1 JetPack Meet-JetPacks',
        file: {
          url: '//videos.ctfassets.net/strhx3d94c40/4T2g8Y5ZWvb41wRGxAlXky/db0102d08588deda54f472bc5ef16d71/1_JetPack_Meet-JetPacks.mp4',
          details: { size: 1042176 },
          fileName: '1_JetPack_Meet-JetPacks.mp4',
          contentType: 'video/mp4',
        },
      },
    },
  },
  {
    product: {
      id: 'blendjet.myshopify.com::jetpack-protein-smoothie::en-us',
      handle: 'jetpack-protein-smoothie',
      locale: 'en-us',
      globalHandle: 'jetpack-protein-smoothie::en-us',
      pimSyncSourceDomain: 'blendjet.myshopify.com',
      title: 'JetPack Protein Smoothie',
      description:
        'Get your protein fix anywhere with our delicious Ready-to-Blend Protein Smoothies. Made with real pieces of freeze-dried fruit and 15g of plant-based protein, JetPack Protein Smoothies are packed with nutrients and bursting with fresh fruit flavor.',
      priceRange: { min: '3.99', max: '3.99', currencyCode: 'USD' },
      availableForSale: true,
      tags: ['JetPack', 'jp', 'protein'],
      media: [
        {
          id: 'Z2lkOi8vc2hvcGlmeS9JbWFnZVNvdXJjZS8yMDI2NDg1ODk0MzU1NA==',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Strawberry-Banana.png?v=1618201477&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Strawberry-Banana.png?v=1618201477',
          type: 'image',
          altText: null,
        },
        {
          id: 'Z2lkOi8vc2hvcGlmeS9JbWFnZVNvdXJjZS8yMDI2NDg1OTM2OTUzOA==',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Peanut-Butter-Power-Breakfast.png?v=1618201477&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Peanut-Butter-Power-Breakfast.png?v=1618201477',
          type: 'image',
          altText: null,
        },
        {
          id: 'Z2lkOi8vc2hvcGlmeS9JbWFnZVNvdXJjZS8yMDI2NDg2MDkwOTYzNA==',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Blueberry-Acai.png?v=1618201477&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Blueberry-Acai.png?v=1618201477',
          type: 'image',
          altText: null,
        },
        {
          id: 'Z2lkOi8vc2hvcGlmeS9JbWFnZVNvdXJjZS8yMDI2NDg1OTg5MzgyNg==',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Orange-Mango-Pineapple.png?v=1618201477&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Orange-Mango-Pineapple.png?v=1618201477',
          type: 'image',
          altText: null,
        },
        {
          id: 'Z2lkOi8vc2hvcGlmeS9JbWFnZVNvdXJjZS8yMDI2NDg1ODU4MzEwNg==',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Very-Berry.png?v=1618201477&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Very-Berry.png?v=1618201477',
          type: 'image',
          altText: null,
        },
        {
          id: 'Z2lkOi8vc2hvcGlmeS9JbWFnZVNvdXJjZS8yMDI2NDg2MDQ4MzY1MA==',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Chocolate-Peanut-Butter-Banana.png?v=1618201477&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Chocolate-Peanut-Butter-Banana.png?v=1618201477',
          type: 'image',
          altText: null,
        },
      ],
      metafields: [
        {
          id: null,
          namespace: 'subscriptions',
          key: 'discount_percentage',
          value: '25.0000000000',
        },
        {
          id: null,
          namespace: 'subscriptions',
          key: 'subscription_id',
          value: '296970',
        },
        {
          id: null,
          namespace: 'subscriptions',
          key: 'shipping_interval_frequency',
          value: '30',
        },
        {
          id: null,
          namespace: 'subscriptions',
          key: 'shipping_interval_unit_type',
          value: 'Days',
        },
        {
          id: null,
          namespace: 'subscriptions',
          key: 'discount_product_id',
          value: '6560019939394',
        },
        {
          id: null,
          namespace: 'subscriptions',
          key: 'is_subscription_only',
          value: 'false',
        },
        {
          id: null,
          namespace: 'subscriptions',
          key: 'original_to_hidden_variant_map',
          value:
            '{"39264793329730": {"discount_variant_id": 39297939800130, "discount_variant_price": "2.99"}, "39264793198658": {"discount_variant_id": 39297939832898, "discount_variant_price": "2.99"}, "39264793231426": {"discount_variant_id": 39297939865666, "discount_variant_price": "2.99"}, "39264793362498": {"discount_variant_id": 39297939898434, "discount_variant_price": "2.99"}, "39264793296962": {"discount_variant_id": 39297939931202, "discount_variant_price": "2.99"}, "39264793264194": {"discount_variant_id": 39297939963970, "discount_variant_price": "2.99"}}',
        },
        { id: null, namespace: 'loox', key: 'num_reviews', value: '422' },
        {
          id: null,
          namespace: 'loox',
          key: 'reviews',
          value:
            '<div id="loox-inline-reviews" style="display:none" data-loox-hash="1638051945844"><div class="review"><div class="name">Bindy W.</div><div class="review_text">It has a great taste.</div></div><div class="review"><div class="name">Lisa M.</div><div class="review_text">Absolutely delicious!!!  Love it</div></div><div class="review"><div class="name">Carole S.</div><div class="review_text">Love love love this thing!!  This is #3 for me now!!\n</div></div><div class="review"><div class="name">Tia T.</div><div class="review_text">I use the protein shakes at work to keep me from snacking on un health items. So far so good!</div></div><div class="review"><div class="name">JULIE H.</div><div class="review_text">.</div></div><div class="review"><div class="name">Ashley P.</div><div class="review_text">Loved how easy and quick you can make smoothies for home and work and when I travel ! Awesome product ! Love it and you will too ! Just try it ! </div></div><div class="review"><div class="name">Lana P.</div><div class="review_text">So amazing!!!</div></div><div class="review"><div class="name">Joanne L.</div><div class="review_text">easy to use, clean, and to travel with. </div></div><div class="review"><div class="name">Jesse L.</div><div class="review_text">Thus o e is one of my favorite ones. It has a great taste and is so easy to make</div></div><div class="review"><div class="name">Jesse L.</div><div class="review_text">This tastes delicious </div></div><div class="review"><div class="name">Jesse L.</div><div class="review_text">This one is my favorite one. It\'s so delicious </div></div><div class="review"><div class="name">Christina  A.</div><div class="review_text">Love the flavor so much. I add a fresh banana to it for extra punch! </div></div><div class="review"><div class="name">Annabelle B.</div><div class="review_text">My favorite. With banana and vegetal milk. </div></div><div class="review"><div class="name">Elvy A.</div><div class="review_text">Sometimes I take it to work too. \nI like how easy it is to prepare </div></div><div class="review"><div class="name">Mr Roy and Mrs Mapula C.</div><div class="review_text">Love , love , love my Blendjet. I use it everyday for my post training shakes. The Jetpack are incredibly delicious and filling. They truly deliver as promised. Thank you for an incredible product Team Blendjet. Love Mapula</div></div><div class="review"><div class="name">Lisa J.</div><div class="review_text">Taste great\n</div></div><div class="review"><div class="name">Gloria M.</div><div class="review_text">I love my Blendjet so much I bought one for all my grand kids for Christmas I know they will love it too. They are athletes and always on the go so this is perfect for them. Thanks Blendhet Team. What an idea!</div></div><div class="review"><div class="name">Tammy L.</div><div class="review_text">I love all the protein smoothie packs but the strawberry banana is a particular favorite!</div></div><div class="review"><div class="name">Tammy L.</div><div class="review_text">Love the ease of making a protein smoothie in the blendjet every morning after our walk!  The are delicious!</div></div><div class="review"><div class="name">Amanda D.</div><div class="review_text">Love blender jetpacks so amazing and convenient. Strawberry banana with some ice and almond milk is so delicious.</div></div><div class="review"><div class="name">nirav g.</div><div class="review_text">i loved it</div></div><div class="review"><div class="name">Ivy G.</div><div class="review_text">I love my blend jet2.. Easy to make my smoothie on the go. And the jetpack are delicious tooo.. Thanks blendjet </div></div><div class="review"><div class="name">Melissa W.</div><div class="review_text">I love these JetPack smoothies! They are so handy and easy to prepare! Very flavorful too!</div></div><div class="review"><div class="name">Melissa W.</div><div class="review_text">These prepackaged smoothies are yummy and so convenient when at home or on the go! </div></div><div class="review"><div class="name">Kristen B.</div><div class="review_text">It so great for &quot; on the go&quot; busy people. I can make my drinks in college classes!!</div></div><div class="review"><div class="name">Raeven Y.</div><div class="review_text">I love the Protein Smoothies.</div></div><div class="review"><div class="name">Joyous J.</div><div class="review_text">I love the taste of the shakes and the convenient of the Blend Jet.</div></div><div class="review"><div class="name">BARRY W.</div><div class="review_text">I travel a lot and don\'t have time or want to sit down for a large breakfast, so my blend jet protein shakes and smoothies are a great  meal replacement! </div></div><div class="review"><div class="name">Sandy K.</div><div class="review_text">This is really the BEST protein shake I\'ve ever had.\nNo aftertaste at all, excellent flavor! Will trying more flavors for sure. Love the Blendjet, always makes the perfect texture drinks</div></div><div class="review"><div class="name">Kristeen L.</div><div class="review_text">Omg this tastes so good and was expecting a chalky taste but noooo it was so yummy</div></div><div class="review"><div class="name">Jazmenn E.</div><div class="review_text">I absolutely LOVE the protein smoothies!!! They are my favorite!!!</div></div><div class="review"><div class="name">JO B.</div><div class="review_text">To my surprise it was delicious, would buy again.</div></div><div class="review"><div class="name">Sarah S.</div><div class="review_text">Love the protein flavors! Highly recommend them! </div></div><div class="review"><div class="name">Ashley R.</div><div class="review_text">Love how easy and convenient this is! Def always with me. Great for work. </div></div><div class="review"><div class="name">Belinda B.</div><div class="review_text">Bought these for my grandson in college.  He lives to have the protein shakes after working out.8</div></div><div class="review"><div class="name">Brett W.</div><div class="review_text">Easy to use and very convenient at work! </div></div><div class="review"><div class="name">Christian  D.</div><div class="review_text">I use my blend jet for açaí bowls and it is bussin bussin</div></div><div class="review"><div class="name">Kathleen D.</div><div class="review_text">They are very filling these shakes </div></div><div class="review"><div class="name">Christiana T.</div><div class="review_text">I love the convenience and ease of use and cleaning! </div></div><div class="review"><div class="name">Roy T.</div><div class="review_text">So easy to use and clean and the smoothie mixes taste great and make you feel full for hours!</div></div><div class="review"><div class="name">Francine U.</div><div class="review_text">I love my BlendJet!</div></div><div class="review"><div class="name">Sara C.</div><div class="review_text">Love it!</div></div><div class="review"><div class="name">debbie c.</div><div class="review_text">i love it</div></div><div class="review"><div class="name">Zoey L.</div><div class="review_text">Fantastic</div></div><div class="review"><div class="name">Kathryn H.</div><div class="review_text">This was the first I tried in the variety pack. It was delicious! The individual packs will be great to take on my upcoming hiking trip.</div></div><div class="review"><div class="name">Kathryn H.</div><div class="review_text">Bought a couple of variety packs (pictured is one variety pack). They are filling and delicious.</div></div><div class="review"><div class="name">Golda S.</div><div class="review_text">I always having my protein shake as my breakfast at work before work.. thanks you so much‍♀️</div></div><div class="review"><div class="name">Susie S.</div><div class="review_text">Love chocolate and peanut butter </div></div><div class="review"><div class="name">Susie S.</div><div class="review_text">Taste so good!</div></div><div class="review"><div class="name">Susie S.</div><div class="review_text">It was delicious!</div></div><div class="review"><div class="name">Malcolm H.</div><div class="review_text">Excellent </div></div><div class="review"><div class="name">Pamela F.</div><div class="review_text">my favorite!!! so delicious </div></div><div class="review"><div class="name">joan i.</div><div class="review_text">The product has lots of flavor. Easy to travel with..</div></div><div class="review"><div class="name">Cheryl C.</div><div class="review_text">Very good.</div></div><div class="review"><div class="name">Ashley G.</div><div class="review_text">Blends so well and makes the best drinks!</div></div><div class="review"><div class="name">Ashley G.</div><div class="review_text">Absolutely the best purchase I’ve made!! </div></div><div class="review"><div class="name">Brenda M.</div><div class="review_text">Delicious, protein drinks! </div></div><div class="review"><div class="name">Agnes A.</div><div class="review_text">I actually have two Blend Jets.  I bought my first one for work.  I loved it so much that I bought a second one for home.  It truly is a space saver and also does not take much time at all to make a smoothie.  I also love several of the flavors.  My favorite one is the Mocha Chia flavor.  I definitely will buy again.  </div></div><div class="review"><div class="name">Lisa K.</div><div class="review_text">Love It !!!</div></div><div class="review"><div class="name">Danielle S.</div><div class="review_text">I love it!</div></div><div class="review"><div class="name">Monika W.</div><div class="review_text">Easy to prepare ! </div></div><div class="review"><div class="name">Mark L.</div><div class="review_text">Love taking it to work. It always turns heads! Love the strawberry banana flavor! Easy to mix different ingredients to make a quick smoothie!\n</div></div><div class="review"><div class="name">Roz P.</div><div class="review_text">I\'ve been drinking protein mixes and smoothies for years and I didn\'t expect too much from these premix packets.  I was w... (10024 total length)',
        },
        { id: null, namespace: 'loox', key: 'avg_rating', value: '5' },
      ],
      variants: [
        {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zOTI2NDc5MzMyOTczMA==',
          title: 'Strawberry Banana',
          price: '3.99',
          priceCurrency: 'USD',
          compareAtPrice: null,
          compareAtPriceCurrency: null,
          swatchSrc: null,
          selectedOptions: [{ name: 'Flavor', value: 'Strawberry Banana' }],
          featuredMedia: {
            id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMjc5Njg4ODkzMjM1ODY=',
            thumbnailSrc:
              'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Strawberry-Banana.png?v=1618201477&width=100',
            src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Strawberry-Banana.png?v=1618201477',
            type: 'image',
            altText: null,
          },
          sku: 'JP-Strawberry-Banana',
          availableForSale: true,
          metafields: [],
          weight: 50,
          weightUnit: 'GRAMS',
          priceRules: null,
        },
        {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zOTI2NDc5MzE5ODY1OA==',
          title: 'Peanut Butter Power Breakfast',
          price: '3.99',
          priceCurrency: 'USD',
          compareAtPrice: null,
          compareAtPriceCurrency: null,
          swatchSrc: null,
          selectedOptions: [
            { name: 'Flavor', value: 'Peanut Butter Power Breakfast' },
          ],
          featuredMedia: {
            id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMjc5Njg4ODk3NDk1NzA=',
            thumbnailSrc:
              'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Peanut-Butter-Power-Breakfast.png?v=1618201477&width=100',
            src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Peanut-Butter-Power-Breakfast.png?v=1618201477',
            type: 'image',
            altText: null,
          },
          sku: 'JP-PB-Power-Breakfast',
          availableForSale: true,
          metafields: [],
          weight: 50,
          weightUnit: 'GRAMS',
          priceRules: null,
        },
        {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zOTI2NDc5MzIzMTQyNg==',
          title: 'Blueberry Acai',
          price: '3.99',
          priceCurrency: 'USD',
          compareAtPrice: null,
          compareAtPriceCurrency: null,
          swatchSrc: null,
          selectedOptions: [{ name: 'Flavor', value: 'Blueberry Acai' }],
          featuredMedia: {
            id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMjc5Njg4OTEyODk2NjY=',
            thumbnailSrc:
              'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Blueberry-Acai.png?v=1618201477&width=100',
            src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Blueberry-Acai.png?v=1618201477',
            type: 'image',
            altText: null,
          },
          sku: 'JP-Blueberry-Acai',
          availableForSale: true,
          metafields: [],
          weight: 50,
          weightUnit: 'GRAMS',
          priceRules: null,
        },
        {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zOTI2NDc5MzI5Njk2Mg==',
          title: 'Very Berry',
          price: '3.99',
          priceCurrency: 'USD',
          compareAtPrice: null,
          compareAtPriceCurrency: null,
          swatchSrc: null,
          selectedOptions: [{ name: 'Flavor', value: 'Very Berry' }],
          featuredMedia: {
            id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMjc5Njg4ODg5NjMxMzg=',
            thumbnailSrc:
              'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Very-Berry.png?v=1618201477&width=100',
            src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Very-Berry.png?v=1618201477',
            type: 'image',
            altText: null,
          },
          sku: 'JP-Very-Berry',
          availableForSale: true,
          metafields: [],
          weight: 50,
          weightUnit: 'GRAMS',
          priceRules: null,
        },
        {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zOTI2NDc5MzI2NDE5NA==',
          title: 'Chocolate Peanut Butter Banana',
          price: '3.99',
          priceCurrency: 'USD',
          compareAtPrice: null,
          compareAtPriceCurrency: null,
          swatchSrc: null,
          selectedOptions: [
            { name: 'Flavor', value: 'Chocolate Peanut Butter Banana' },
          ],
          featuredMedia: {
            id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMjc5Njg4OTA4NjM2ODI=',
            thumbnailSrc:
              'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Chocolate-Peanut-Butter-Banana.png?v=1618201477&width=100',
            src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Chocolate-Peanut-Butter-Banana.png?v=1618201477',
            type: 'image',
            altText: null,
          },
          sku: 'JP-Chocolate-PB-Banana',
          availableForSale: true,
          metafields: [],
          weight: 50,
          weightUnit: 'GRAMS',
          priceRules: null,
        },
      ],
      indexedAt: 1638192714,
      pimSyncSource: 'shopify',
      pimSyncSourceProductId:
        'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzY1NDU2NDE0NzIwNjY=',
      productType: 'Jetpack Smoothies',
      featuredMedia: {
        id: 'Z2lkOi8vc2hvcGlmeS9JbWFnZVNvdXJjZS8yMDI2NDg1ODk0MzU1NA==',
        thumbnailSrc:
          'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Strawberry-Banana.png?v=1618201477&width=100',
        src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Strawberry-Banana.png?v=1618201477',
        type: 'image',
        altText: null,
      },
      vendor: 'BlendJet',
      createdAt: 1615860103,
    },
    variants: [
      {
        id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zOTI2NDc5MzMyOTczMA==',
        title: 'Strawberry Banana',
        price: '3.99',
        priceCurrency: 'USD',
        compareAtPrice: null,
        compareAtPriceCurrency: null,
        swatchSrc: null,
        selectedOptions: [{ name: 'Flavor', value: 'Strawberry Banana' }],
        featuredMedia: {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMjc5Njg4ODkzMjM1ODY=',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Strawberry-Banana.png?v=1618201477&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Strawberry-Banana.png?v=1618201477',
          type: 'image',
          altText: null,
        },
        sku: 'JP-Strawberry-Banana',
        availableForSale: true,
        metafields: [],
        weight: 50,
        weightUnit: 'GRAMS',
        priceRules: null,
      },
      {
        id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zOTI2NDc5MzE5ODY1OA==',
        title: 'Peanut Butter Power Breakfast',
        price: '3.99',
        priceCurrency: 'USD',
        compareAtPrice: null,
        compareAtPriceCurrency: null,
        swatchSrc: null,
        selectedOptions: [
          { name: 'Flavor', value: 'Peanut Butter Power Breakfast' },
        ],
        featuredMedia: {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMjc5Njg4ODk3NDk1NzA=',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Peanut-Butter-Power-Breakfast.png?v=1618201477&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Peanut-Butter-Power-Breakfast.png?v=1618201477',
          type: 'image',
          altText: null,
        },
        sku: 'JP-PB-Power-Breakfast',
        availableForSale: true,
        metafields: [],
        weight: 50,
        weightUnit: 'GRAMS',
        priceRules: null,
      },
      {
        id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zOTI2NDc5MzIzMTQyNg==',
        title: 'Blueberry Acai',
        price: '3.99',
        priceCurrency: 'USD',
        compareAtPrice: null,
        compareAtPriceCurrency: null,
        swatchSrc: null,
        selectedOptions: [{ name: 'Flavor', value: 'Blueberry Acai' }],
        featuredMedia: {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMjc5Njg4OTEyODk2NjY=',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Blueberry-Acai.png?v=1618201477&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Blueberry-Acai.png?v=1618201477',
          type: 'image',
          altText: null,
        },
        sku: 'JP-Blueberry-Acai',
        availableForSale: true,
        metafields: [],
        weight: 50,
        weightUnit: 'GRAMS',
        priceRules: null,
      },
      {
        id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zOTI2NDc5MzI5Njk2Mg==',
        title: 'Very Berry',
        price: '3.99',
        priceCurrency: 'USD',
        compareAtPrice: null,
        compareAtPriceCurrency: null,
        swatchSrc: null,
        selectedOptions: [{ name: 'Flavor', value: 'Very Berry' }],
        featuredMedia: {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMjc5Njg4ODg5NjMxMzg=',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Very-Berry.png?v=1618201477&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Very-Berry.png?v=1618201477',
          type: 'image',
          altText: null,
        },
        sku: 'JP-Very-Berry',
        availableForSale: true,
        metafields: [],
        weight: 50,
        weightUnit: 'GRAMS',
        priceRules: null,
      },
      {
        id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zOTI2NDc5MzI2NDE5NA==',
        title: 'Chocolate Peanut Butter Banana',
        price: '3.99',
        priceCurrency: 'USD',
        compareAtPrice: null,
        compareAtPriceCurrency: null,
        swatchSrc: null,
        selectedOptions: [
          { name: 'Flavor', value: 'Chocolate Peanut Butter Banana' },
        ],
        featuredMedia: {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMjc5Njg4OTA4NjM2ODI=',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Chocolate-Peanut-Butter-Banana.png?v=1618201477&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Protein-Smoothie_Chocolate-Peanut-Butter-Banana.png?v=1618201477',
          type: 'image',
          altText: null,
        },
        sku: 'JP-Chocolate-PB-Banana',
        availableForSale: true,
        metafields: [],
        weight: 50,
        weightUnit: 'GRAMS',
        priceRules: null,
      },
    ],
    title: 'BLENDJET 2 + SLEEVE + 6 JETPACKS',
    media: {
      metadata: { tags: [] },
      sys: {
        space: { sys: { type: 'Link', linkType: 'Space', id: 'strhx3d94c40' } },
        id: '59eVaa3yRvuWauhF9nJnNU',
        type: 'Asset',
        createdAt: '2021-04-11T20:49:18.826Z',
        updatedAt: '2021-04-12T02:17:33.754Z',
        environment: {
          sys: { id: 'master', type: 'Link', linkType: 'Environment' },
        },
        revision: 2,
        locale: 'en-US',
      },
      fields: {
        title: 'jetpackprotein1',
        file: {
          url: '//videos.ctfassets.net/strhx3d94c40/59eVaa3yRvuWauhF9nJnNU/9573530968714093cdfa75e0b9fedbc1/LOOP_1__NEW__1.mp4',
          details: { size: 1006200 },
          fileName: 'LOOP 1 (NEW)_1.mp4',
          contentType: 'video/mp4',
        },
      },
    },
  },
];

export const bundles = [
  {
    product: {
      id: 'blendjet.myshopify.com::jetsetter-insulated-sleeve::en-us',
      handle: 'jetsetter-insulated-sleeve',
      locale: 'en-us',
      globalHandle: 'jetsetter-insulated-sleeve::en-us',
      pimSyncSourceDomain: 'blendjet.myshopify.com',
      title: 'Jetsetter Insulated Sleeve',
      description:
        'Take your smoothie to go! Slip your BlendJet into this protective insulated pouch to keep your drink’s chill factor. Ideal for stashing your portable blender in your gym bag, purse or suitcase, or bringing something to sip on your commute.<br data-mce-fragment="1"><br data-mce-fragment="1"><strong>JETSETTER INSULATED SLEEVE FEATURES:</strong><br data-mce-fragment="1">\n<ul>\n<li>Designed to hold your BlendJet One or 2</li>\n<li>Constructed with durable, high quality materials to protect your BlendJet</li>\n<li>Provides hours-worth of insulation to keep your ingredients cold</li>\n<li>Water-repellent fabric</li>\n<li>Zippered top closure</li>\n<li>Built-in wrist strap makes it easy to carry</li>\n<li>Easy to clean</li>\n</ul>\n<strong>MATERIALS &amp; CARE:</strong><br data-mce-fragment="1">\n<ul>\n<li>Body: Durable water-repellent coated nylon</li>\n<li>Lining: Durable water-repellent coated polyester fabric</li>\n<li>1 cm thick closed-cell poly foam insulation</li>\n<li>Wipe clean with a damp cloth. Do not wash or dry clean.</li>\n</ul>\n<strong>DETAILS &amp; SPECS:</strong><br data-mce-fragment="1">\n<ul>\n<li>Designed to fit both BlendJet One and BlendJet 2</li>\n<li>Dimensions: 3.5” x 3.5” x 11 (9cm x 9cm x 28cm)</li>\n<li>Weight: 2.4 oz (70.9 mL)</li>\n<li>Volume: 1.6L</li>\n</ul>',
      priceRange: { min: '14.95', max: '14.95', currencyCode: 'USD' },
      availableForSale: true,
      tags: [
        'bag',
        'bags',
        'exclude-product',
        'insulated',
        'jetsetter',
        'sleeve',
      ],
      media: [
        {
          id: 'Z2lkOi8vc2hvcGlmeS9JbWFnZVNvdXJjZS83MTU2NDMxNDIxNTA2',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Black-Sleeve_Website_Thumbnail.png?v=1613756333&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Black-Sleeve_Website_Thumbnail.png?v=1613756333',
          type: 'image',
          altText: 'Jetsetter Insulated Sleeve in Black',
        },
        {
          id: 'Z2lkOi8vc2hvcGlmeS9JbWFnZVNvdXJjZS83MTU2NDMxMzU1OTcw',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Mint-Sleeve_Website_Thumbnail.png?v=1613757041&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Mint-Sleeve_Website_Thumbnail.png?v=1613757041',
          type: 'image',
          altText: 'Jetsetter Insulated Sleeve in Mint',
        },
        {
          id: 'Z2lkOi8vc2hvcGlmeS9JbWFnZVNvdXJjZS83MTU2NDMxMzg4NzM4',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Lavender-Sleeve_Website_Thumbnail.png?v=1606363993&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Lavender-Sleeve_Website_Thumbnail.png?v=1606363993',
          type: 'image',
          altText: null,
        },
        {
          id: 'Z2lkOi8vc2hvcGlmeS9JbWFnZVNvdXJjZS8yMDg4Nzg3NDc5NzYzNA==',
          thumbnailSrc:
            'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Royal-Blue-Sleeve_Website_Thumbnail.png?v=1636522885&width=100',
          src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Royal-Blue-Sleeve_Website_Thumbnail.png?v=1636522885',
          type: 'image',
          altText: null,
        },
      ],
      metafields: [
        { id: null, namespace: 'loox', key: 'avg_rating', value: '5' },
        { id: null, namespace: 'loox', key: 'num_reviews', value: '641' },
        {
          id: null,
          namespace: 'loox',
          key: 'reviews',
          value:
            '<div id="loox-inline-reviews" style="display:none" data-loox-hash="1637717158610"><div class="review"><div class="name">Tiffany M.</div><div class="review_text">It’s easy and portable.  Love it. Gonna buy one for family for Christmas </div></div><div class="review"><div class="name">Francesca H.</div><div class="review_text">This insulated sleeve is really handy when I have to drink my smoothies on the run!</div></div><div class="review"><div class="name">Pegah A.</div><div class="review_text">love my blendjet 2 and the insulated sleeve!</div></div><div class="review"><div class="name">Kristine A.</div><div class="review_text">I love the bag</div></div><div class="review"><div class="name">Kim H.</div><div class="review_text">Take it on the go and make my shakes! ❤️</div></div><div class="review"><div class="name">Daniel M.</div><div class="review_text">Very good product </div></div><div class="review"><div class="name">Caren M.</div><div class="review_text">This is awesome! It really well made! It keeps my drink cold! And it’s very well padded! Great for travel!</div></div><div class="review"><div class="name">Christine L.</div><div class="review_text">great!!!!</div></div><div class="review"><div class="name">Lupita G.</div><div class="review_text">SOOO Convenient!! Insulated sleeve a MUST-HAVE. Keeps Blendjet2 protected...</div></div><div class="review"><div class="name">Hugo C.</div><div class="review_text">Great little portable blender good for smoothies or shakes! </div></div><div class="review"><div class="name">Stacy M.</div><div class="review_text">Cool!!!</div></div><div class="review"><div class="name">Beth P.</div><div class="review_text">Love it</div></div><div class="review"><div class="name">Cynthia D.</div><div class="review_text">I love this item it makes me feel so much safer toting my blend jet with me wherever I go!</div></div><div class="review"><div class="name">Melissa W.</div><div class="review_text">I love my new Blendjet sleeve for keeping my device safe and handy for travel! It just slips right in and away we both go! </div></div><div class="review"><div class="name">Roslyn B.</div><div class="review_text">i use this to protect my blender while travelling. And keep the fruits cool before i blend</div></div><div class="review"><div class="name">Ruth B.</div><div class="review_text">Great and easy to use </div></div><div class="review"><div class="name">Tracy G.</div><div class="review_text">I love this cover not only protects your blendjet but it keeps it nice and cold for your next fresh fruit juice</div></div><div class="review"><div class="name">Ledarius J.</div><div class="review_text">Love the bag it helps out a lot with carrying it around.  \n</div></div><div class="review"><div class="name">John M.</div><div class="review_text">Not only does it protect my blendjet, it keeps the contents cold while I take it on the go. I think it would also contain a leak caused by not tightening components completely if it ever happened.</div></div><div class="review"><div class="name">Andrew A.</div><div class="review_text">i love my blendjet and blendjet case, i use it all the time. i want to get a couple more jet tag keychains for my blendjet case too.</div></div><div class="review"><div class="name">Jason B.</div><div class="review_text">Great carrying case for on the go</div></div><div class="review"><div class="name">Cilla C.</div><div class="review_text">Love it keeps stuff cold for ages</div></div><div class="review"><div class="name">Wendy C.</div><div class="review_text">My insulater works well, keeps my almond Milk cold </div></div><div class="review"><div class="name">Tracey D.</div><div class="review_text">Perfect case for storing the Blendjet. </div></div><div class="review"><div class="name">Anisah R.</div><div class="review_text">Perfect!</div></div><div class="review"><div class="name">Ana M.</div><div class="review_text">Love ❤️ </div></div><div class="review"><div class="name">Nina E.</div><div class="review_text">Cover is fitting perfectly and keeps my blendr in safe</div></div><div class="review"><div class="name">Jeff F.</div><div class="review_text">Great product.</div></div><div class="review"><div class="name">Jean T.</div><div class="review_text">Love it</div></div><div class="review"><div class="name">Myles M.</div><div class="review_text">Love it </div></div><div class="review"><div class="name">Naomi H.</div><div class="review_text">Love this accompaniment to the matching blendjet..</div></div><div class="review"><div class="name">Hamed a.</div><div class="review_text">A wonderful and strong wallet, that enables you to preserve the device from breakage and scratches\n</div></div><div class="review"><div class="name">Xia Rain T.</div><div class="review_text">Great cover, very nice quality material. Fits the blend jet snugly. The little tab to put it around your wrist is great for travel. </div></div><div class="review"><div class="name">Philip L.</div><div class="review_text">I love how easy it is to clean. </div></div><div class="review"><div class="name">joel m.</div><div class="review_text">Veey cool</div></div><div class="review"><div class="name">jessica n.</div><div class="review_text">Perfect!</div></div><div class="review"><div class="name">ANGELITA D.</div><div class="review_text">Love the sleeve protector to bring my blendjet on the go</div></div><div class="review"><div class="name">Sue S.</div><div class="review_text">I absolutely love making my protein shakes in this and bringing to work with me and putting right in the sleeve to keep cool’ </div></div><div class="review"><div class="name">Zoey L.</div><div class="review_text">Fantastic for the blender.</div></div><div class="review"><div class="name">Angelina L.</div><div class="review_text">Just buy it!!! I can\'t say enough great things about it!!</div></div><div class="review"><div class="name">Leanne B.</div><div class="review_text">Love it, quick,quite, take anywhere</div></div><div class="review"><div class="name">Nanette H.</div><div class="review_text">Great way to take drinks on our boat! </div></div><div class="review"><div class="name">Susie S.</div><div class="review_text">It keeps my smoothies cold.  </div></div><div class="review"><div class="name">Joseph M.</div><div class="review_text">This is a game changer and a must buy. I use it to have a smoothie for lunch while at work. It is easy to clip onto your bag and keep your smoothie nice and cold. Being busy and on the go, this help to keep my on my diet. </div></div><div class="review"><div class="name">Karen  S.</div><div class="review_text">Living in a hot place the insulated sleeve for my blendjet is great addition to transport to work\n</div></div><div class="review"><div class="name">Sara  H.</div><div class="review_text">Travel case is perfect </div></div><div class="review"><div class="name">Jason M.</div><div class="review_text">Keeps the ingredients cold on the way to work, it\'s very helpful</div></div><div class="review"><div class="name">Kirsten G.</div><div class="review_text">I love blend jet products. I love to make smoothies, milk shakes, lattes, protein shakes, frappe’s and mocha. And I love the green tea mocha.</div></div><div class="review"><div class="name">Tracy S.</div><div class="review_text">I love my BlendJet2. And the carrying case is just perfect. Best way to carry it to work. Lots of space for the charging cord. Glad I ordered it with the case.</div></div><div class="review"><div class="name">Janet N.</div><div class="review_text">I would have wanted it in the same pink color as my blender but this lavender color is beautiful and I love how it protects the blender and it’s charging cord.  </div></div><div class="review"><div class="name">LaKetra H.</div><div class="review_text">Super duper great</div></div><div class="review"><div class="name">Donna M.</div><div class="review_text">I have a number of blending devices and this little mauve darling is on the counter beside my Vitamix!  It’s great for basic smoothies &amp; very portable.  I bought the sleeve which offers protection if I am taking it with me.  Great little blender!</div></div><div class="review"><div class="name">Danyell H.</div><div class="review_text">Keeps smoothies cold until I am ready!</div></div><div class="review"><div class="name">Elena C.</div><div class="review_text">I put all my ingredients into my Blendjet and take it to work in the insulated pouch. Perfect in 40 degree morning weather in Doha. </div></div><div class="review"><div class="name">Connie C.</div><div class="review_text">The sleeve keeps my blender looking brand new and keeps my ingredients cold!!</div></div><div class="review"><div class="name">Tamara B.</div><div class="review_text">I love the insulated sleeve. It definitely keeps my smoothies cool. </div></div><div class="review"><div class="name">Victoria P.</div><div class="review_text">This insulated case was a great buy - you can either blend smoothies at home then keep them cold for a few hours, or you can keep the ingredients cold and then blend when you\'re ready to eat! And it protects the blendjet too ❤️ highly recommended! </div></div><div class="review"><div class="name">Tonja C.</div><div class="review_text">I put my shakes together in my Blendjet and then put it in the sleeve it\'s convenient and keeps everything cool. </div></div><div class="review"><div class="name">paul k.</div><div class="review_text">I love my blendjets. I also have a travel cases for them… my suggestion would be to put a small pocket on the travel case for the power cords other than that I am enjoying it every day thank you guys!!</div></div><div class="review"><div class="name">Pat H.</div><div class="review_text">Love the Blendjet. So easy to use.</div></div><div class="review"><div class="name">Letty H.</div><div class="review_text">Keeps my shake very cold \n\n\n\n\n\n\n</div></div><div class="review"><div class="name">Naomi T.</div><div class=... (10024 total length)',
        },
      ],
      variants: [
        {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zMjU1NzIxNjY5NDMzOA==',
          title: 'Black',
          price: '14.95',
          priceCurrency: 'USD',
          compareAtPrice: '19.95',
          compareAtPriceCurrency: '19.95',
          swatchSrc: null,
          selectedOptions: [{ name: 'Color', value: 'Black' }],
          featuredMedia: {
            id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMTQ5ODI0ODMzNzgyNDI=',
            thumbnailSrc:
              'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Black-Sleeve_Website_Thumbnail.png?v=1613756333&width=100',
            src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Black-Sleeve_Website_Thumbnail.png?v=1613756333',
            type: 'image',
            altText: 'Jetsetter Insulated Sleeve in Black',
          },
          sku: 'black-sleeve',
          availableForSale: true,
          metafields: [],
          weight: null,
          weightUnit: null,
          priceRules: null,
        },
        {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zMjU1NzIxNjcyNzEwNg==',
          title: 'Mint',
          price: '14.95',
          priceCurrency: 'USD',
          compareAtPrice: '19.95',
          compareAtPriceCurrency: '19.95',
          swatchSrc: null,
          selectedOptions: [{ name: 'Color', value: 'Mint' }],
          featuredMedia: {
            id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMTQ5ODI0ODMzNDU0NzQ=',
            thumbnailSrc:
              'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Mint-Sleeve_Website_Thumbnail.png?v=1613757041&width=100',
            src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Mint-Sleeve_Website_Thumbnail.png?v=1613757041',
            type: 'image',
            altText: 'Jetsetter Insulated Sleeve in Mint',
          },
          sku: 'mint-sleeve',
          availableForSale: true,
          metafields: [],
          weight: null,
          weightUnit: null,
          priceRules: null,
        },
        {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zMjU1NzIxNjc1OTg3NA==',
          title: 'Lavender',
          price: '14.95',
          priceCurrency: 'USD',
          compareAtPrice: '19.95',
          compareAtPriceCurrency: '19.95',
          swatchSrc: null,
          selectedOptions: [{ name: 'Color', value: 'Lavender' }],
          featuredMedia: {
            id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMTQ5ODI0ODMyNDcxNzA=',
            thumbnailSrc:
              'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Lavender-Sleeve_Website_Thumbnail.png?v=1606363993&width=100',
            src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Lavender-Sleeve_Website_Thumbnail.png?v=1606363993',
            type: 'image',
            altText: null,
          },
          sku: 'lavender-sleeve',
          availableForSale: true,
          metafields: [],
          weight: null,
          weightUnit: null,
          priceRules: null,
        },
        {
          id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zOTYwNDgwOTYyOTc2Mg==',
          title: 'Royal Blue',
          price: '14.95',
          priceCurrency: 'USD',
          compareAtPrice: '19.95',
          compareAtPriceCurrency: '19.95',
          swatchSrc: null,
          selectedOptions: [{ name: 'Color', value: 'Royal Blue' }],
          featuredMedia: {
            id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMjg1NzY5Mzg2NTU4MTA=',
            thumbnailSrc:
              'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Royal-Blue-Sleeve_Website_Thumbnail.png?v=1636522885&width=100',
            src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Royal-Blue-Sleeve_Website_Thumbnail.png?v=1636522885',
            type: 'image',
            altText: null,
          },
          sku: 'royal-blue-sleeve',
          availableForSale: true,
          metafields: [],
          weight: null,
          weightUnit: null,
          priceRules: null,
        },
      ],
      indexedAt: 1637758351,
      pimSyncSource: 'shopify',
      pimSyncSourceProductId:
        'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ3MTI3OTI3NTIxOTQ=',
      productType: 'Jetsetter',
      featuredMedia: {
        id: 'Z2lkOi8vc2hvcGlmeS9JbWFnZVNvdXJjZS83MTU2NDMxNDIxNTA2',
        thumbnailSrc:
          'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Black-Sleeve_Website_Thumbnail.png?v=1613756333&width=100',
        src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Black-Sleeve_Website_Thumbnail.png?v=1613756333',
        type: 'image',
        altText: 'Jetsetter Insulated Sleeve in Black',
      },
      vendor: 'BlendJet',
      createdAt: 1603686439,
    },
    variant: {
      id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC8zMjU1NzIxNjY5NDMzOA==',
      title: 'Black',
      price: '14.95',
      priceCurrency: 'USD',
      compareAtPrice: '19.95',
      compareAtPriceCurrency: '19.95',
      swatchSrc: null,
      selectedOptions: [{ name: 'Color', value: 'Black' }],
      featuredMedia: {
        id: 'Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMTQ5ODI0ODMzNzgyNDI=',
        thumbnailSrc:
          'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Black-Sleeve_Website_Thumbnail.png?v=1613756333&width=100',
        src: 'https://cdn.shopify.com/s/files/1/0066/4433/4658/products/Black-Sleeve_Website_Thumbnail.png?v=1613756333',
        type: 'image',
        altText: 'Jetsetter Insulated Sleeve in Black',
      },
      sku: 'black-sleeve',
      availableForSale: true,
      metafields: [],
      weight: null,
      weightUnit: null,
      priceRules: null,
    },
    title: 'BLENDJET 2 + SLEEVE + 6 JETPACKS',
    clickAction: 'variant',
    media: {
      metadata: { tags: [] },
      sys: {
        space: { sys: { type: 'Link', linkType: 'Space', id: 'strhx3d94c40' } },
        id: '4uIQ0QTvWMSp8nTWwgWU3n',
        type: 'Asset',
        createdAt: '2020-11-25T19:08:22.633Z',
        updatedAt: '2020-11-25T19:08:22.633Z',
        environment: {
          sys: { id: 'master', type: 'Link', linkType: 'Environment' },
        },
        revision: 1,
        locale: 'en-US',
      },
      fields: {
        title: 'Jetsetter Sleeve Animation',
        file: {
          url: '//videos.ctfassets.net/strhx3d94c40/4uIQ0QTvWMSp8nTWwgWU3n/24ef58e0ae9fb1f426c111defd4fd668/Jetsetter-Sleeve-Animation.mp4',
          details: { size: 702942 },
          fileName: 'Jetsetter-Sleeve-Animation.mp4',
          contentType: 'video/mp4',
        },
      },
    },
    variantsAvailableForSale: 4,
  },
];
