name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install && cd outsmartly/content-sources && npm install && cd ../../
      - name: Check formatting
        run: npm run format-check
      - name: Typechecking
        run: npm run tsc
